
from ast import Try
from logging import raiseExceptions




# try: #tente isso
#     print(x)
# except: #se der errado aparece isso
#     print('Ocorreu um erro')
# else: #se der certo aparece isso
#     print('Estou no else')

# finally: #aparece mesmo se der certo ou errado
#     print('Estou no finally')


#     o erro pode ser especificado e tratado assim

# try:
#     print(0/0)
# except ZeroDivisionError:
#     print('Não é possivel dividir por 0')
# except NameError:
#     print('Variavel não definida')


# assim posso fazer para mostrar um erro ao usuario

# x = -10

# if x < 0:
#     raise Exception('O numero não pode se menor que 0')